# Optional native dialog dependency for wl2_slint. The helper intentionally
# returns "not found" instead of failing for provider=auto on unsupported or
# dependency-light targets, so embedded builds can keep wl2_slint enabled.
include_guard(GLOBAL)

function(_wl2_nfd_supported out_supported out_reason)
    if(CMAKE_SYSTEM_NAME STREQUAL "Windows" OR CMAKE_SYSTEM_NAME STREQUAL "Darwin")
        set(${out_supported} TRUE PARENT_SCOPE)
        set(${out_reason} "" PARENT_SCOPE)
        return()
    endif()

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        find_package(PkgConfig QUIET)
        if(PkgConfig_FOUND)
            pkg_check_modules(WL2_SLINT_NFD_DBUS QUIET dbus-1)
            if(WL2_SLINT_NFD_DBUS_FOUND)
                set(${out_supported} TRUE PARENT_SCOPE)
                set(${out_reason} "" PARENT_SCOPE)
                return()
            endif()
        endif()
        set(${out_supported} FALSE PARENT_SCOPE)
        set(${out_reason} "Linux native dialogs need dbus-1 development files for NFDe portal mode" PARENT_SCOPE)
        return()
    endif()

    set(${out_supported} FALSE PARENT_SCOPE)
    set(${out_reason} "nativefiledialog-extended is not enabled for ${CMAKE_SYSTEM_NAME}" PARENT_SCOPE)
endfunction()

function(_wl2_nfd_target_exists out_target)
    if(TARGET nfd)
        set(${out_target} nfd PARENT_SCOPE)
    elseif(TARGET nfd::nfd)
        set(${out_target} nfd::nfd PARENT_SCOPE)
    elseif(TARGET nativefiledialog-extended)
        set(${out_target} nativefiledialog-extended PARENT_SCOPE)
    else()
        set(${out_target} "" PARENT_SCOPE)
    endif()
endfunction()

macro(_wl2_nfd_with_deprecation_warnings_disabled)
    set(_wl2_nfd_old_warn_deprecated "${CMAKE_WARN_DEPRECATED}")
    set(_wl2_nfd_old_policy_version_minimum "${CMAKE_POLICY_VERSION_MINIMUM}")
    set(CMAKE_WARN_DEPRECATED OFF)
    set(CMAKE_POLICY_VERSION_MINIMUM 3.10)
endmacro()

macro(_wl2_nfd_restore_deprecation_warnings)
    set(CMAKE_WARN_DEPRECATED "${_wl2_nfd_old_warn_deprecated}")
    set(CMAKE_POLICY_VERSION_MINIMUM "${_wl2_nfd_old_policy_version_minimum}")
    unset(_wl2_nfd_old_warn_deprecated)
    unset(_wl2_nfd_old_policy_version_minimum)
endmacro()

function(wl2_find_nfd)
    include("${CMAKE_CURRENT_LIST_DIR}/options.cmake" OPTIONAL)

    set(WL2_HAVE_NFD FALSE PARENT_SCOPE)
    set(WL2_NFD_TARGET "" PARENT_SCOPE)
    set(WL2_NFD_PROVIDER_USED "" PARENT_SCOPE)

    if(NOT WL2_SLINT_NATIVE_DIALOGS OR WL2_SLINT_NFD_PROVIDER STREQUAL "off")
        message(STATUS "wl2_slint native dialogs disabled")
        return()
    endif()

    _wl2_nfd_supported(_supported _reason)
    if(NOT _supported)
        if(WL2_SLINT_NFD_PROVIDER STREQUAL "auto")
            message(STATUS "wl2_slint native dialogs disabled: ${_reason}")
            return()
        endif()
        message(FATAL_ERROR "wl2_slint native dialogs requested but unsupported: ${_reason}")
    endif()

    if(WL2_SLINT_NFD_PROVIDER STREQUAL "local" OR WL2_SLINT_NFD_PROVIDER STREQUAL "auto")
        if(WL2_SLINT_NFD_ROOT AND EXISTS "${WL2_SLINT_NFD_ROOT}/CMakeLists.txt")
            set(NFD_BUILD_TESTS OFF CACHE BOOL "" FORCE)
            set(NFD_INSTALL OFF CACHE BOOL "" FORCE)
            if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
                set(NFD_PORTAL ON CACHE BOOL "" FORCE)
            endif()
            _wl2_nfd_with_deprecation_warnings_disabled()
            add_subdirectory("${WL2_SLINT_NFD_ROOT}" "${CMAKE_BINARY_DIR}/wl2_slint_nfd_local")
            _wl2_nfd_restore_deprecation_warnings()
            _wl2_nfd_target_exists(_target)
            if(_target)
                set(WL2_HAVE_NFD TRUE PARENT_SCOPE)
                set(WL2_NFD_TARGET "${_target}" PARENT_SCOPE)
                set(WL2_NFD_PROVIDER_USED local PARENT_SCOPE)
                message(STATUS "Using local nativefiledialog-extended from ${WL2_SLINT_NFD_ROOT}")
                return()
            endif()
        endif()
        if(WL2_SLINT_NFD_PROVIDER STREQUAL "local")
            message(FATAL_ERROR "WL2_SLINT_NFD_PROVIDER=local but nativefiledialog-extended was not found under ${WL2_SLINT_NFD_ROOT}")
        endif()
    endif()

    if(WL2_SLINT_NFD_PROVIDER STREQUAL "package" OR WL2_SLINT_NFD_PROVIDER STREQUAL "auto")
        find_package(nfd CONFIG QUIET)
        _wl2_nfd_target_exists(_target)
        if(_target)
            set(WL2_HAVE_NFD TRUE PARENT_SCOPE)
            set(WL2_NFD_TARGET "${_target}" PARENT_SCOPE)
            set(WL2_NFD_PROVIDER_USED package PARENT_SCOPE)
            message(STATUS "Using package/system nativefiledialog-extended")
            return()
        endif()
        if(WL2_SLINT_NFD_PROVIDER STREQUAL "package")
            message(FATAL_ERROR "WL2_SLINT_NFD_PROVIDER=package but nativefiledialog-extended was not found")
        endif()
    endif()

    if(WL2_SLINT_NFD_PROVIDER STREQUAL "fetch" OR (WL2_SLINT_NFD_PROVIDER STREQUAL "auto" AND WL2_FETCH_DEPS))
        if(NOT WL2_FETCH_DEPS AND WL2_SLINT_NFD_PROVIDER STREQUAL "fetch")
            message(FATAL_ERROR "WL2_SLINT_NFD_PROVIDER=fetch but WL2_FETCH_DEPS=OFF")
        endif()
        include(FetchContent)
        set(FETCHCONTENT_BASE_DIR "${WL2_DEPS_ROOT}/_fetch" CACHE PATH "FetchContent base directory" FORCE)
        set(NFD_BUILD_TESTS OFF CACHE BOOL "" FORCE)
        set(NFD_INSTALL OFF CACHE BOOL "" FORCE)
        if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
            set(NFD_PORTAL ON CACHE BOOL "" FORCE)
        endif()
        FetchContent_Declare(nativefiledialog_extended
            GIT_REPOSITORY "${WL2_SLINT_NFD_GIT_REPOSITORY}"
            GIT_TAG "${WL2_SLINT_NFD_GIT_TAG}")
        _wl2_nfd_with_deprecation_warnings_disabled()
        FetchContent_MakeAvailable(nativefiledialog_extended)
        _wl2_nfd_restore_deprecation_warnings()
        _wl2_nfd_target_exists(_target)
        if(_target)
            set(WL2_HAVE_NFD TRUE PARENT_SCOPE)
            set(WL2_NFD_TARGET "${_target}" PARENT_SCOPE)
            set(WL2_NFD_PROVIDER_USED fetch PARENT_SCOPE)
            message(STATUS "Using fetched nativefiledialog-extended ${WL2_SLINT_NFD_GIT_TAG}")
            return()
        endif()
        if(WL2_SLINT_NFD_PROVIDER STREQUAL "fetch")
            message(FATAL_ERROR "Fetched nativefiledialog-extended did not create an nfd target")
        endif()
    endif()

    message(STATUS "nativefiledialog-extended not found; wl2_slint native dialogs disabled")
endfunction()
