include_guard(GLOBAL)

# A macro, not a function: it sets the renderer-result variables with
# PARENT_SCOPE, and is invoked from wl2_find_magnum(). As a macro it inlines into
# wl2_find_magnum(), so PARENT_SCOPE resolves to wl2_find_magnum()'s caller (the
# module CMakeLists), which is where WL2_3D_HAVE_MAGNUM / WL2_3D_MAGNUM_TARGETS
# must land. A function would set them only in wl2_find_magnum()'s own scope,
# leaving the module built with the renderer compiled out.
macro(_wl2_3d_set_magnum_result provider)
    set(WL2_3D_HAVE_MAGNUM TRUE PARENT_SCOPE)
    # Scope the Magnum link to the build tree. In-tree consumers (the wl2 app and
    # the module tests) link Magnum normally, but the installed/exported
    # wl2_3d_static interface must not carry these source-built (non-imported)
    # targets: install(EXPORT) requires every LINK_ONLY dependency to be in an
    # export set, and Corrade/Magnum are built EXCLUDE_FROM_ALL and not exported.
    # (The "package" provider's imported Magnum::* targets are skipped by that
    # check anyway, so BUILD_INTERFACE is correct for every provider.) Out-of-tree
    # renderer builds re-resolve Magnum through this same helper rather than the
    # winglib2 export set.
    set(WL2_3D_MAGNUM_TARGETS
        $<BUILD_INTERFACE:Magnum::Magnum>
        $<BUILD_INTERFACE:Magnum::GL>
        $<BUILD_INTERFACE:Magnum::WindowlessEglApplication>
        PARENT_SCOPE)
    set(WL2_3D_MAGNUM_PROVIDER_USED "${provider}" PARENT_SCOPE)
endmacro()

function(_wl2_3d_try_package out_var)
    find_package(Corrade QUIET COMPONENTS Utility)
    find_package(Magnum QUIET COMPONENTS GL WindowlessEglApplication)
    if(TARGET Magnum::Magnum AND TARGET Magnum::GL AND TARGET Magnum::WindowlessEglApplication)
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

macro(_wl2_3d_with_third_party_warnings_disabled)
    set(_wl2_3d_old_warn_deprecated "${CMAKE_WARN_DEPRECATED}")
    set(_wl2_3d_old_suppress_dev "${CMAKE_SUPPRESS_DEVELOPER_WARNINGS}")
    set(_wl2_3d_old_cxx_flags "${CMAKE_CXX_FLAGS}")
    get_property(_wl2_3d_had_warn_deprecated CACHE CMAKE_WARN_DEPRECATED PROPERTY VALUE SET)
    get_property(_wl2_3d_had_suppress_dev CACHE CMAKE_SUPPRESS_DEVELOPER_WARNINGS PROPERTY VALUE SET)
    set(CMAKE_WARN_DEPRECATED OFF)
    set(CMAKE_SUPPRESS_DEVELOPER_WARNINGS ON)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        string(APPEND CMAKE_CXX_FLAGS " -Wno-cpp")
    endif()
    set(CMAKE_WARN_DEPRECATED OFF CACHE BOOL "Suppress third-party dependency deprecation warnings" FORCE)
    set(CMAKE_SUPPRESS_DEVELOPER_WARNINGS ON CACHE INTERNAL "Suppress third-party dependency developer warnings" FORCE)
endmacro()

macro(_wl2_3d_restore_third_party_warnings)
    set(CMAKE_WARN_DEPRECATED "${_wl2_3d_old_warn_deprecated}")
    set(CMAKE_SUPPRESS_DEVELOPER_WARNINGS "${_wl2_3d_old_suppress_dev}")
    set(CMAKE_CXX_FLAGS "${_wl2_3d_old_cxx_flags}")
    if(_wl2_3d_had_warn_deprecated)
        set(CMAKE_WARN_DEPRECATED "${_wl2_3d_old_warn_deprecated}" CACHE BOOL "Whether to issue deprecation warnings for macros and functions" FORCE)
    else()
        unset(CMAKE_WARN_DEPRECATED CACHE)
    endif()
    if(_wl2_3d_had_suppress_dev)
        set(CMAKE_SUPPRESS_DEVELOPER_WARNINGS "${_wl2_3d_old_suppress_dev}" CACHE INTERNAL "Suppress developer warnings" FORCE)
    else()
        unset(CMAKE_SUPPRESS_DEVELOPER_WARNINGS CACHE)
    endif()
    unset(_wl2_3d_old_warn_deprecated)
    unset(_wl2_3d_old_suppress_dev)
    unset(_wl2_3d_old_cxx_flags)
    unset(_wl2_3d_had_warn_deprecated)
    unset(_wl2_3d_had_suppress_dev)
endmacro()

function(_wl2_3d_try_local out_var)
    set(_wl2_deps_root "${WL2_DEPS_ROOT}/src")
    set(_wl2_corrade_source "${_wl2_deps_root}/corrade-${WL2_MAGNUM_VERSION}")
    set(_wl2_magnum_source "${_wl2_deps_root}/magnum-${WL2_MAGNUM_VERSION}")

    if(NOT EXISTS "${_wl2_corrade_source}/CMakeLists.txt" OR NOT EXISTS "${_wl2_magnum_source}/CMakeLists.txt")
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()

    set(BUILD_TESTS OFF CACHE BOOL "Build dependency tests" FORCE)
    set(BUILD_STATIC ON CACHE BOOL "Build static dependencies" FORCE)
    set(BUILD_STATIC_PIC ON CACHE BOOL "Build position-independent static dependencies" FORCE)
    set(CMAKE_POLICY_VERSION_MINIMUM 3.5 CACHE STRING "Minimum CMake policy version for legacy dependency projects" FORCE)

    set(WITH_INTERCONNECT OFF CACHE BOOL "" FORCE)
    set(WITH_PLUGINMANAGER OFF CACHE BOOL "" FORCE)
    set(WITH_TESTSUITE OFF CACHE BOOL "" FORCE)
    set(WITH_UTILITY ON CACHE BOOL "" FORCE)
    set(WITH_MAIN OFF CACHE BOOL "" FORCE)
    set(WITH_RC OFF CACHE BOOL "" FORCE)

    if(NOT TARGET Corrade::Utility)
        _wl2_3d_with_third_party_warnings_disabled()
        add_subdirectory("${_wl2_corrade_source}" "${CMAKE_BINARY_DIR}/_deps/corrade-2020.06" EXCLUDE_FROM_ALL)
        _wl2_3d_restore_third_party_warnings()
    endif()

    set(WITH_AUDIO OFF CACHE BOOL "" FORCE)
    set(WITH_DEBUGTOOLS OFF CACHE BOOL "" FORCE)
    set(WITH_MESHTOOLS OFF CACHE BOOL "" FORCE)
    set(WITH_PRIMITIVES OFF CACHE BOOL "" FORCE)
    set(WITH_SCENEGRAPH OFF CACHE BOOL "" FORCE)
    set(WITH_SHADERS OFF CACHE BOOL "" FORCE)
    set(WITH_TEXT OFF CACHE BOOL "" FORCE)
    set(WITH_TEXTURETOOLS OFF CACHE BOOL "" FORCE)
    set(WITH_TRADE OFF CACHE BOOL "" FORCE)
    set(WITH_GL ON CACHE BOOL "" FORCE)
    set(WITH_VK OFF CACHE BOOL "" FORCE)
    set(WITH_WINDOWLESSEGLAPPLICATION ON CACHE BOOL "" FORCE)
    set(WITH_EGLCONTEXT OFF CACHE BOOL "" FORCE)
    set(WITH_GL_INFO OFF CACHE BOOL "" FORCE)
    set(WITH_IMAGECONVERTER OFF CACHE BOOL "" FORCE)
    set(WITH_SCENECONVERTER OFF CACHE BOOL "" FORCE)

    if(NOT TARGET Magnum::WindowlessEglApplication)
        _wl2_3d_with_third_party_warnings_disabled()
        add_subdirectory("${_wl2_magnum_source}" "${CMAKE_BINARY_DIR}/_deps/magnum-2020.06" EXCLUDE_FROM_ALL)
        _wl2_3d_restore_third_party_warnings()
    endif()

    if(TARGET Magnum::Magnum AND TARGET Magnum::GL AND TARGET Magnum::WindowlessEglApplication)
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(_wl2_3d_download_archive name url hash out_var)
    set(${out_var} "" PARENT_SCOPE)
    set(_archive "${WL2_DEPS_ROOT}/src/${name}-${WL2_MAGNUM_VERSION}.tar.gz")
    set(_source_root "${WL2_DEPS_ROOT}/src/${name}-${WL2_MAGNUM_VERSION}")

    if(EXISTS "${_source_root}/CMakeLists.txt")
        set(${out_var} "${_source_root}" PARENT_SCOPE)
        return()
    endif()

    file(MAKE_DIRECTORY "${WL2_DEPS_ROOT}/src")
    if(NOT EXISTS "${_archive}")
        message(STATUS "Fetching ${name} ${WL2_MAGNUM_VERSION} from ${url}")
        set(_download_args "${url}" "${_archive}" SHOW_PROGRESS STATUS _download_status)
        if(hash)
            list(APPEND _download_args EXPECTED_HASH "${hash}")
        endif()
        file(DOWNLOAD ${_download_args})
        list(GET _download_status 0 _download_code)
        if(NOT _download_code EQUAL 0)
            list(GET _download_status 1 _download_message)
            message(STATUS "${name} download failed: ${_download_message}")
            return()
        endif()
    endif()

    file(ARCHIVE_EXTRACT INPUT "${_archive}" DESTINATION "${WL2_DEPS_ROOT}/src")
    if(EXISTS "${_source_root}/CMakeLists.txt")
        set(${out_var} "${_source_root}" PARENT_SCOPE)
    endif()
endfunction()

function(_wl2_3d_fetch_sources out_var)
    _wl2_3d_download_archive(corrade "${WL2_CORRADE_URL}" "${WL2_CORRADE_URL_HASH}" _corrade_source)
    _wl2_3d_download_archive(magnum "${WL2_MAGNUM_URL}" "${WL2_MAGNUM_URL_HASH}" _magnum_source)
    if(_corrade_source AND _magnum_source)
        set(${out_var} TRUE PARENT_SCOPE)
    else()
        set(${out_var} FALSE PARENT_SCOPE)
    endif()
endfunction()

function(wl2_find_magnum)
    include("${CMAKE_CURRENT_LIST_DIR}/options.cmake" OPTIONAL)

    set(WL2_3D_HAVE_MAGNUM FALSE PARENT_SCOPE)
    set(WL2_3D_MAGNUM_TARGETS "" PARENT_SCOPE)
    set(WL2_3D_MAGNUM_PROVIDER_USED "" PARENT_SCOPE)

    if(WL2_3D_PROVIDER STREQUAL "off")
        message(STATUS "WL2_3D_PROVIDER=off; wl2_3d renderer disabled")
        wl2_dependency_note_result(magnum DISABLED "WL2_DEPS_MAGNUM=off")
        return()
    endif()

    if(WL2_3D_PROVIDER STREQUAL "package")
        _wl2_3d_try_package(_wl2_package_found)
        if(NOT _wl2_package_found)
            message(FATAL_ERROR "WL2_3D_PROVIDER=package requested, but Corrade/Magnum packages were not found")
        endif()
        _wl2_3d_set_magnum_result("package")
        wl2_dependency_note_result(magnum system "Magnum::WindowlessEglApplication")
        message(STATUS "wl2_3d renderer enabled with packaged Magnum")
        return()
    endif()

    if(WL2_3D_PROVIDER STREQUAL "local")
        _wl2_3d_try_local(_wl2_local_found)
        if(NOT _wl2_local_found)
            message(FATAL_ERROR "WL2_3D_PROVIDER=local requested, but local Corrade/Magnum sources were not found under ${WL2_DEPS_ROOT}/src")
        endif()
        _wl2_3d_set_magnum_result("local")
        wl2_dependency_note_result(magnum local "${WL2_DEPS_ROOT}/src")
        message(STATUS "wl2_3d renderer enabled with local Magnum sources")
        return()
    endif()

    if(WL2_3D_PROVIDER STREQUAL "fetch")
        _wl2_3d_fetch_sources(_wl2_fetched)
        if(NOT _wl2_fetched)
            message(FATAL_ERROR "WL2_3D_PROVIDER=fetch requested, but Corrade/Magnum could not be downloaded")
        endif()
        _wl2_3d_try_local(_wl2_local_found)
        if(NOT _wl2_local_found)
            message(FATAL_ERROR "WL2_3D_PROVIDER=fetch downloaded Corrade/Magnum, but the renderer targets were not created")
        endif()
        _wl2_3d_set_magnum_result("fetch")
        wl2_dependency_note_result(magnum download "${WL2_MAGNUM_VERSION} ${WL2_DEPS_ROOT}/src")
        message(STATUS "wl2_3d renderer enabled with downloaded Magnum sources")
        return()
    endif()

    if(WL2_3D_PROVIDER STREQUAL "auto")
        _wl2_3d_try_local(_wl2_local_found)
        if(_wl2_local_found)
            _wl2_3d_set_magnum_result("local")
            wl2_dependency_note_result(magnum local "${WL2_DEPS_ROOT}/src")
            message(STATUS "wl2_3d renderer enabled with local Magnum sources")
            return()
        endif()
        _wl2_3d_fetch_sources(_wl2_fetched)
        if(_wl2_fetched)
            _wl2_3d_try_local(_wl2_local_found)
            if(_wl2_local_found)
                _wl2_3d_set_magnum_result("fetch")
                wl2_dependency_note_result(magnum download "${WL2_MAGNUM_VERSION} ${WL2_DEPS_ROOT}/src")
                message(STATUS "wl2_3d renderer enabled with downloaded Magnum sources")
                return()
            endif()
        endif()
        _wl2_3d_try_package(_wl2_package_found)
        if(_wl2_package_found)
            _wl2_3d_set_magnum_result("package")
            wl2_dependency_note_result(magnum system "Magnum::WindowlessEglApplication")
            message(STATUS "wl2_3d renderer enabled with packaged Magnum")
            return()
        endif()
        message(STATUS "WL2_3D_PROVIDER=auto; no Corrade/Magnum provider found, wl2_3d renderer disabled")
        wl2_dependency_note_result(magnum DISABLED "not found")
        return()
    endif()

    message(FATAL_ERROR "Unsupported WL2_3D_PROVIDER=${WL2_3D_PROVIDER}; expected auto, local, package, fetch, or off")
endfunction()
