include_guard(GLOBAL)
set(_WL2_ONVIF_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(wl2_find_onvif)
    include("${_WL2_ONVIF_CMAKE_DIR}/options.cmake")
    set(_found OFF)

    if(WL2_ONVIF_PROVIDER STREQUAL "off")
        set(WL2_HAVE_ONVIF OFF PARENT_SCOPE)
        return()
    endif()

    if(WL2_ONVIF_PROVIDER STREQUAL "local" OR WL2_ONVIF_PROVIDER STREQUAL "auto")
        if(EXISTS "${WL2_ONVIF_ROOT}/CMakeLists.txt")
            set(WLONVIF_BUILD_TESTING OFF CACHE BOOL "" FORCE)
            set(WLONVIF_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
            set(WLONVIF_BUILD_FUZZERS OFF CACHE BOOL "" FORCE)
            set(WLONVIF_BUILD_DOCS OFF CACHE BOOL "" FORCE)
            set(WLONVIF_BUILD_PTZ_CONTROL OFF CACHE BOOL "" FORCE)
            set(WLONVIF_BUILD_PTZ_WEB OFF CACHE BOOL "" FORCE)
            add_subdirectory("${WL2_ONVIF_ROOT}" "${CMAKE_BINARY_DIR}/_deps/wlonvif-local")
            set(_found ON)
        else()
            find_package(wlonvif CONFIG QUIET COMPONENTS client
                PATHS "${WL2_ONVIF_ROOT}" NO_DEFAULT_PATH)
            if(TARGET wlonvif::client)
                set(_found ON)
            elseif(WL2_ONVIF_PROVIDER STREQUAL "local")
                message(FATAL_ERROR "WL2_ONVIF_PROVIDER=local but wlonvif was not found at ${WL2_ONVIF_ROOT}")
            endif()
        endif()
    endif()

    if(NOT _found AND (WL2_ONVIF_PROVIDER STREQUAL "package" OR WL2_ONVIF_PROVIDER STREQUAL "auto"))
        find_package(wlonvif CONFIG QUIET COMPONENTS client)
        if(TARGET wlonvif::client)
            set(_found ON)
        elseif(WL2_ONVIF_PROVIDER STREQUAL "package")
            message(FATAL_ERROR "WL2_ONVIF_PROVIDER=package but wlonvif::client was not found")
        endif()
    endif()

    if(NOT _found AND (WL2_ONVIF_PROVIDER STREQUAL "fetch" OR WL2_ONVIF_PROVIDER STREQUAL "auto"))
        include(FetchContent)
        set(WLONVIF_BUILD_TESTING OFF CACHE BOOL "" FORCE)
        set(WLONVIF_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
        set(WLONVIF_BUILD_FUZZERS OFF CACHE BOOL "" FORCE)
        set(WLONVIF_BUILD_DOCS OFF CACHE BOOL "" FORCE)
        set(WLONVIF_BUILD_PTZ_CONTROL OFF CACHE BOOL "" FORCE)
        set(WLONVIF_BUILD_PTZ_WEB OFF CACHE BOOL "" FORCE)
        set(WLONVIF_FETCH_PTZ_DEPENDENCIES OFF CACHE BOOL "" FORCE)
        FetchContent_Declare(wlonvif URL "${WL2_ONVIF_URL}" URL_HASH "${WL2_ONVIF_URL_HASH}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
        FetchContent_MakeAvailable(wlonvif)
        set(_found ON)
    endif()

    set(WL2_HAVE_ONVIF "${_found}" PARENT_SCOPE)
    if(_found)
        set(WL2_ONVIF_TARGET wlonvif::client PARENT_SCOPE)
    endif()
endfunction()
