include("${CMAKE_CURRENT_LIST_DIR}/deps/WL2Dependency.cmake")

option(WL2_BUILD_TESTING "Build Winglib2 tests" ON)
option(WL2_BUILD_SHARED_MODULES "Build dynamic WL2 modules" OFF)
option(WL2_BUILD_STATIC_MODULES "Build static WL2 modules" ON)
option(WL2_BUILD_EXAMPLES "Build Winglib2 examples" ON)
option(WL2_BUILD_OUTOFTREE_TESTS "Register the out-of-tree module install/build test" ON)
option(WL2_BUILD_DOCS "Build Doxygen API documentation" ON)
option(WL2_ENABLE_STRESS_TESTS "Register opt-in stress tests with CTest" OFF)
option(WL2_ENABLE_LIBMEMBUS "Build first-class libmembus shared-memory wrappers when available" ON)
option(WL2_ENABLE_EXTENDED_MODULES "Build extended modules by default" ON)
option(WL2_ENABLE_ALL_MODULES "Build every discovered module in the source tree unless listed in WL2_DISABLE_MODULES" OFF)
option(WL2_ENABLE_V8 "Compatibility option: build with WL2_JS_ENGINE=v8" OFF)
option(WL2_FETCH_DEPS "Deprecated compatibility option; use WL2_DEPS instead" ON)
option(WL2_USE_FETCHED_DEPS "Deprecated compatibility option; use WL2_DEPS=download instead" OFF)
wl2_dependency_configure_global_default()

set(WL2_JS_ENGINE "quickjs" CACHE STRING "JavaScript engine backend: quickjs or v8")
set_property(CACHE WL2_JS_ENGINE PROPERTY STRINGS quickjs v8)
set(WL2_DISABLE_MODULES "" CACHE STRING "Semicolon-separated module directories or provided module names to skip")
set(WL2_EXTRA_MODULE_DIRS "" CACHE STRING "Semicolon-separated additional module source directories")

set(WL2_QUICKJS_ROOT "" CACHE PATH "Path containing QuickJS include/ and lib/")
set(WL2_QUICKJS_PROVIDER "auto" CACHE STRING "QuickJS provider: auto, local, package, fetch, or off")
set_property(CACHE WL2_QUICKJS_PROVIDER PROPERTY STRINGS auto local package fetch off)
set(WL2_QUICKJS_VERSION "2025-09-13-2" CACHE STRING "QuickJS release version")
set(WL2_QUICKJS_URL "https://bellard.org/quickjs/quickjs-${WL2_QUICKJS_VERSION}.tar.xz" CACHE STRING "QuickJS source archive URL")

set(WL2_V8_ROOT "" CACHE PATH "Path containing V8 include/ and lib/libv8_monolith.a")
set(WL2_V8_PROVIDER "auto" CACHE STRING "V8 provider: auto, local, package, or off")
set_property(CACHE WL2_V8_PROVIDER PROPERTY STRINGS auto local package off)
set(WL2_V8_EXTRA_LIBRARIES "" CACHE STRING "Additional libraries required by the selected V8 build")

set(WL2_LIBMEMBUS_TARGET_VERSION "2.1.0" CACHE STRING "Target libmembus API version for Winglib2 integration")
set(WL2_LIBMEMBUS_PROVIDER "auto" CACHE STRING "libmembus provider: auto, local, package, fetch, or off")
set_property(CACHE WL2_LIBMEMBUS_PROVIDER PROPERTY STRINGS auto local package fetch off)

wl2_dependency_configure_provider(QUICKJS WL2_QUICKJS_PROVIDER)
wl2_dependency_configure_provider(LIBMEMBUS WL2_LIBMEMBUS_PROVIDER)

function(wl2_configure_dependency_options)
    if(NOT WL2_DEPS_ROOT)
        message(FATAL_ERROR "wl2_configure_dependency_options requires WL2_DEPS_ROOT")
    endif()

    set(WL2_LIBMEMBUS_ROOT "${WL2_DEPS_ROOT}/libmembus" CACHE PATH "Path to a target-local libmembus checkout")
endfunction()
