include("${CMAKE_CURRENT_LIST_DIR}/deps/WL2Dependency.cmake")

option(WL2_BUILD_TESTING "Build Winglib2 tests" ON)
set(WL2_MODULE_LINKAGE "both" CACHE STRING "Module artifacts to build: dynamic, static, or both")
set_property(CACHE WL2_MODULE_LINKAGE PROPERTY STRINGS dynamic static both)
if(WL2_MODULE_LINKAGE STREQUAL "dynamic")
    set(_wl2_default_shared_modules ON)
    set(_wl2_default_static_modules OFF)
elseif(WL2_MODULE_LINKAGE STREQUAL "static")
    set(_wl2_default_shared_modules OFF)
    set(_wl2_default_static_modules ON)
elseif(WL2_MODULE_LINKAGE STREQUAL "both")
    set(_wl2_default_shared_modules ON)
    set(_wl2_default_static_modules ON)
else()
    message(FATAL_ERROR "WL2_MODULE_LINKAGE must be dynamic, static, or both")
endif()
set(WL2_BUILD_SHARED_MODULES "${_wl2_default_shared_modules}" CACHE BOOL "Build dynamic WL2 modules" FORCE)
set(WL2_BUILD_STATIC_MODULES "${_wl2_default_static_modules}" CACHE BOOL "Build static WL2 modules" FORCE)
# Runner and example module modes follow the linkage: a static-only build gets
# a static (builtin) runner and static examples; both/dynamic default to the
# dynamic module store. An explicit -D on either mode overrides the default.
if(WL2_MODULE_LINKAGE STREQUAL "static")
    set(_wl2_default_module_mode "static")
else()
    set(_wl2_default_module_mode "dynamic")
endif()
set(WL2_WL2_MODULE_MODE "${_wl2_default_module_mode}" CACHE STRING "wl2 runner module mode: dynamic, static, or dynamic-with-static-fallback")
set_property(CACHE WL2_WL2_MODULE_MODE PROPERTY STRINGS dynamic static dynamic-with-static-fallback)
set(WL2_EXAMPLES_MODULE_MODE "${_wl2_default_module_mode}" CACHE STRING "Example module mode: dynamic or static")
set_property(CACHE WL2_EXAMPLES_MODULE_MODE PROPERTY STRINGS dynamic static)
if(NOT WL2_WL2_MODULE_MODE STREQUAL "dynamic"
        AND NOT WL2_WL2_MODULE_MODE STREQUAL "static"
        AND NOT WL2_WL2_MODULE_MODE STREQUAL "dynamic-with-static-fallback")
    message(FATAL_ERROR "WL2_WL2_MODULE_MODE must be dynamic, static, or dynamic-with-static-fallback")
endif()
if(WL2_WL2_MODULE_MODE STREQUAL "static" AND NOT WL2_BUILD_STATIC_MODULES)
    message(FATAL_ERROR "WL2_WL2_MODULE_MODE=static requires WL2_BUILD_STATIC_MODULES=ON")
endif()
if(WL2_WL2_MODULE_MODE STREQUAL "dynamic" AND NOT WL2_BUILD_SHARED_MODULES)
    message(FATAL_ERROR "WL2_WL2_MODULE_MODE=dynamic requires WL2_BUILD_SHARED_MODULES=ON")
endif()
if(WL2_WL2_MODULE_MODE STREQUAL "dynamic-with-static-fallback" AND NOT WL2_BUILD_STATIC_MODULES)
    message(FATAL_ERROR "WL2_WL2_MODULE_MODE=dynamic-with-static-fallback requires static modules (WL2_MODULE_LINKAGE=static or both)")
endif()
if(WL2_WL2_MODULE_MODE STREQUAL "dynamic-with-static-fallback" AND NOT WL2_BUILD_SHARED_MODULES)
    message(FATAL_ERROR "WL2_WL2_MODULE_MODE=dynamic-with-static-fallback requires dynamic modules (WL2_MODULE_LINKAGE=dynamic or both)")
endif()
if(WL2_EXAMPLES_MODULE_MODE STREQUAL "static" AND NOT WL2_BUILD_STATIC_MODULES)
    message(FATAL_ERROR "WL2_EXAMPLES_MODULE_MODE=static requires static modules (WL2_MODULE_LINKAGE=static or both)")
endif()
if(WL2_EXAMPLES_MODULE_MODE STREQUAL "dynamic" AND NOT WL2_BUILD_SHARED_MODULES)
    message(FATAL_ERROR "WL2_EXAMPLES_MODULE_MODE=dynamic requires dynamic modules (WL2_MODULE_LINKAGE=dynamic or both)")
endif()
option(WL2_BUILD_EXAMPLES "Build Winglib2 examples" ON)
option(WL2_BUILD_OUTOFTREE_TESTS "Register the out-of-tree module install/build test" ON)
option(WL2_BUILD_DOCS "Build Doxygen API documentation" ON)
option(WL2_ENABLE_STRESS_TESTS "Register opt-in stress tests with CTest" OFF)
option(WL2_ENABLE_LIBMEMBUS "Build first-class libmembus shared-memory wrappers when available" ON)
option(WL2_ENABLE_EXTENDED_MODULES "Build extended modules by default" ON)
option(WL2_ENABLE_ALL_MODULES "Build every discovered module in the source tree unless listed in WL2_DISABLE_MODULES" OFF)
option(WL2_ENABLE_V8 "Compatibility option: build with WL2_JS_ENGINE=v8" OFF)
option(WL2_FETCH_DEPS "Deprecated compatibility option; use WL2_DEPS instead" ON)
option(WL2_USE_FETCHED_DEPS "Deprecated compatibility option; use WL2_DEPS=download instead" OFF)
wl2_dependency_configure_global_default()

set(WL2_JS_ENGINE "quickjs" CACHE STRING "JavaScript engine backend: quickjs or v8")
set_property(CACHE WL2_JS_ENGINE PROPERTY STRINGS quickjs v8)
set(WL2_DISABLE_MODULES "" CACHE STRING "Semicolon-separated module directories or provided module names to skip")
set(WL2_EXTRA_MODULE_DIRS "" CACHE STRING "Semicolon-separated additional module source directories")

set(WL2_QUICKJS_ROOT "" CACHE PATH "Path containing QuickJS include/ and lib/")
set(WL2_QUICKJS_PROVIDER "auto" CACHE STRING "QuickJS provider: auto, local, package, fetch, or off")
set_property(CACHE WL2_QUICKJS_PROVIDER PROPERTY STRINGS auto local package fetch off)
set(WL2_QUICKJS_VERSION "2025-09-13-2" CACHE STRING "QuickJS release version")
set(WL2_QUICKJS_URL "https://bellard.org/quickjs/quickjs-${WL2_QUICKJS_VERSION}.tar.xz" CACHE STRING "QuickJS source archive URL")

set(WL2_V8_ROOT "" CACHE PATH "Path containing V8 include/ and lib/libv8_monolith.a")
set(WL2_V8_PROVIDER "auto" CACHE STRING "V8 provider: auto, local, package, or off")
set_property(CACHE WL2_V8_PROVIDER PROPERTY STRINGS auto local package off)
set(WL2_V8_EXTRA_LIBRARIES "" CACHE STRING "Additional libraries required by the selected V8 build")

set(WL2_LIBMEMBUS_TARGET_VERSION "2.1.0" CACHE STRING "Target libmembus API version for Winglib2 integration")
set(WL2_LIBMEMBUS_PROVIDER "auto" CACHE STRING "libmembus provider: auto, local, package, fetch, or off")
set_property(CACHE WL2_LIBMEMBUS_PROVIDER PROPERTY STRINGS auto local package fetch off)

set(WL2_NLOHMANN_JSON_ROOT "" CACHE PATH "Path containing nlohmann/json.hpp or include/nlohmann/json.hpp")
set(WL2_NLOHMANN_JSON_PROVIDER "auto" CACHE STRING "nlohmann_json provider: auto, local, package, fetch, or off")
set_property(CACHE WL2_NLOHMANN_JSON_PROVIDER PROPERTY STRINGS auto local package fetch off)
set(WL2_NLOHMANN_JSON_VERSION "3.11.3" CACHE STRING "nlohmann_json release version")
set(WL2_NLOHMANN_JSON_URL "https://github.com/nlohmann/json/releases/download/v${WL2_NLOHMANN_JSON_VERSION}/json.tar.xz" CACHE STRING "nlohmann_json source archive URL")

wl2_dependency_configure_provider(QUICKJS WL2_QUICKJS_PROVIDER)
wl2_dependency_configure_provider(LIBMEMBUS WL2_LIBMEMBUS_PROVIDER)
wl2_dependency_configure_provider(NLOHMANN_JSON WL2_NLOHMANN_JSON_PROVIDER)

function(wl2_configure_dependency_options)
    if(NOT WL2_DEPS_ROOT)
        message(FATAL_ERROR "wl2_configure_dependency_options requires WL2_DEPS_ROOT")
    endif()

    set(WL2_LIBMEMBUS_ROOT "${WL2_DEPS_ROOT}/libmembus" CACHE PATH "Path to a target-local libmembus checkout")
    set(WL2_NLOHMANN_JSON_ROOT "${WL2_DEPS_ROOT}/nlohmann_json" CACHE PATH "Path to a target-local nlohmann_json checkout")
endfunction()
