function(wl2_byte_to_hex value out_var)
    set(_digits 0 1 2 3 4 5 6 7 8 9 a b c d e f)
    math(EXPR _high "${value} / 16")
    math(EXPR _low "${value} % 16")
    list(GET _digits ${_high} _high_hex)
    list(GET _digits ${_low} _low_hex)
    set(${out_var} "${_high_hex}${_low_hex}" PARENT_SCOPE)
endfunction()

function(wl2_rle_encode_hex input_hex out_hex)
    string(LENGTH "${input_hex}" _hex_len)
    set(_encoded "")
    set(_pos 0)
    while(_pos LESS _hex_len)
        string(SUBSTRING "${input_hex}" ${_pos} 2 _byte)
        set(_count 1)
        math(EXPR _next "${_pos} + 2")
        while(_next LESS _hex_len AND _count LESS 255)
            string(SUBSTRING "${input_hex}" ${_next} 2 _next_byte)
            if(NOT _next_byte STREQUAL _byte)
                break()
            endif()
            math(EXPR _count "${_count} + 1")
            math(EXPR _next "${_next} + 2")
        endwhile()
        wl2_byte_to_hex(${_count} _count_hex)
        string(APPEND _encoded "${_count_hex}${_byte}")
        set(_pos ${_next})
    endwhile()
    set(${out_hex} "${_encoded}" PARENT_SCOPE)
endfunction()

function(wl2_append_resource_array output ident content_hex)
    file(APPEND "${output}" "const unsigned char res_${ident}[] = {")
    string(LENGTH "${content_hex}" _hex_len)
    if(_hex_len GREATER 0)
        math(EXPR _last "${_hex_len} - 2")
        foreach(_pos RANGE 0 ${_last} 2)
            string(SUBSTRING "${content_hex}" ${_pos} 2 _byte)
            file(APPEND "${output}" "0x${_byte},")
        endforeach()
    else()
        # Zero-length arrays are not standard C++; emit a single placeholder byte.
        # The registration below records the real (zero) length, so the
        # placeholder is never read.
        file(APPEND "${output}" "0x00,")
    endif()
    file(APPEND "${output}" "};\n")
endfunction()

function(wl2_glob_to_regex pattern out_var)
    string(REGEX REPLACE "([][+.^$(){}|\\\\])" "\\\\\\1" _regex "${pattern}")
    string(REPLACE "*" ".*" _regex "${_regex}")
    string(REPLACE "?" "." _regex "${_regex}")
    set(${out_var} "^${_regex}$" PARENT_SCOPE)
endfunction()

function(wl2_cpp_escape_string input out_var)
    string(REPLACE "\\" "\\\\" _escaped "${input}")
    string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
    string(REPLACE "\n" "\\n" _escaped "${_escaped}")
    set(${out_var} "${_escaped}" PARENT_SCOPE)
endfunction()

function(wl2_manifest_append_value var value)
    string(STRIP "${value}" _value)
    string(REGEX REPLACE "^['\"](.*)['\"]$" "\\1" _value "${_value}")
    if(_value STREQUAL "")
        message(FATAL_ERROR "Manifest list value cannot be empty")
    endif()
    set(${var} ${${var}} "${_value}" PARENT_SCOPE)
endfunction()

function(wl2_read_resource_manifest manifest_path out_prefix)
    if(NOT EXISTS "${manifest_path}")
        message(FATAL_ERROR "Manifest does not exist: ${manifest_path}")
    endif()
    get_filename_component(_manifest_dir "${manifest_path}" DIRECTORY)
    file(STRINGS "${manifest_path}" _lines)

    set(_schema)
    set(_root)
    set(_prefix "wl2:/app")
    set(_entry)
    set(_store_files)
    set(_compress_files)
    set(_auto_files)
    set(_store_directories)
    set(_compress_directories)
    set(_auto_directories)
    set(_exclude_patterns)
    set(_section)
    set(_policy)
    set(_list_key)

    foreach(_line IN LISTS _lines)
        string(REGEX REPLACE "#.*$" "" _line "${_line}")
        if(_line MATCHES "^[ \t]*$")
            continue()
        endif()
        string(LENGTH "${_line}" _line_len)
        string(REGEX MATCH "^ *" _indent_text "${_line}")
        string(LENGTH "${_indent_text}" _indent)
        string(STRIP "${_line}" _text)

        if(_text MATCHES "^- +(.*)$")
            set(_value "${CMAKE_MATCH_1}")
            if(_section STREQUAL "exclude")
                wl2_manifest_append_value(_exclude_patterns "${_value}")
            elseif(_section STREQUAL "resources")
                if(_policy STREQUAL "store")
                    if(_list_key STREQUAL "directories")
                        wl2_manifest_append_value(_store_directories "${_value}")
                    else()
                        wl2_manifest_append_value(_store_files "${_value}")
                    endif()
                elseif(_policy STREQUAL "compress")
                    if(_list_key STREQUAL "directories")
                        wl2_manifest_append_value(_compress_directories "${_value}")
                    else()
                        wl2_manifest_append_value(_compress_files "${_value}")
                    endif()
                elseif(_policy STREQUAL "auto")
                    if(_list_key STREQUAL "directories")
                        wl2_manifest_append_value(_auto_directories "${_value}")
                    else()
                        wl2_manifest_append_value(_auto_files "${_value}")
                    endif()
                else()
                    message(FATAL_ERROR "Manifest resource list without policy: ${manifest_path}")
                endif()
            endif()
            continue()
        endif()

        if(NOT _text MATCHES "^([^:]+):(.*)$")
            message(FATAL_ERROR "Invalid manifest line: ${_text}")
        endif()
        string(STRIP "${CMAKE_MATCH_1}" _key)
        string(STRIP "${CMAKE_MATCH_2}" _value)
        string(REGEX REPLACE "^['\"](.*)['\"]$" "\\1" _value "${_value}")

        if(_indent EQUAL 0)
            set(_section "${_key}")
            set(_policy)
            set(_list_key)
            if(_key STREQUAL "schema")
                set(_schema "${_value}")
            elseif(_key STREQUAL "root")
                set(_root "${_value}")
            elseif(_key STREQUAL "prefix")
                set(_prefix "${_value}")
            elseif(_key STREQUAL "entry")
                set(_entry "${_value}")
            elseif(_key STREQUAL "resources" OR _key STREQUAL "exclude" OR _key STREQUAL "modules" OR _key STREQUAL "tests" OR _key STREQUAL "dependencies")
            else()
                message(FATAL_ERROR "Unknown manifest key: ${_key}")
            endif()
        elseif(_section STREQUAL "resources" AND _indent EQUAL 2)
            if(NOT _key STREQUAL "store" AND NOT _key STREQUAL "compress" AND NOT _key STREQUAL "auto")
                message(FATAL_ERROR "Unknown manifest resources policy: ${_key}")
            endif()
            set(_policy "${_key}")
            set(_list_key)
        elseif(_section STREQUAL "resources" AND _indent EQUAL 4)
            if(NOT _key STREQUAL "files" AND NOT _key STREQUAL "directories")
                message(FATAL_ERROR "Expected files or directories in manifest resources")
            endif()
            set(_list_key "${_key}")
        endif()
    endforeach()

    if(NOT _schema STREQUAL "wl2.resources.v1" AND NOT _schema STREQUAL "wl2.project.v1")
        message(FATAL_ERROR "Unsupported manifest schema: ${_schema}")
    endif()
    if(NOT _root)
        message(FATAL_ERROR "Manifest root is required: ${manifest_path}")
    endif()
    if(NOT _entry)
        message(FATAL_ERROR "Manifest entry is required: ${manifest_path}")
    endif()
    if(IS_ABSOLUTE "${_root}")
        set(_resolved_root "${_root}")
    else()
        set(_resolved_root "${_manifest_dir}/${_root}")
    endif()

    set(${out_prefix}_ROOT "${_resolved_root}" PARENT_SCOPE)
    set(${out_prefix}_PREFIX "${_prefix}" PARENT_SCOPE)
    set(${out_prefix}_ENTRY "${_entry}" PARENT_SCOPE)
    set(${out_prefix}_STORE_FILES "${_store_files}" PARENT_SCOPE)
    set(${out_prefix}_COMPRESS_FILES "${_compress_files}" PARENT_SCOPE)
    set(${out_prefix}_AUTO_FILES "${_auto_files}" PARENT_SCOPE)
    set(${out_prefix}_STORE_DIRECTORIES "${_store_directories}" PARENT_SCOPE)
    set(${out_prefix}_COMPRESS_DIRECTORIES "${_compress_directories}" PARENT_SCOPE)
    set(${out_prefix}_AUTO_DIRECTORIES "${_auto_directories}" PARENT_SCOPE)
    set(${out_prefix}_EXCLUDE_PATTERNS "${_exclude_patterns}" PARENT_SCOPE)
endfunction()

function(wl2_add_embedded_resources target_name)
    set(options)
    set(oneValueArgs ROOT PREFIX OUTPUT COMPRESSION)
    set(multiValueArgs
        FILES STORE_FILES COMPRESS_FILES AUTO_FILES
        DIRECTORIES STORE_DIRECTORIES COMPRESS_DIRECTORIES AUTO_DIRECTORIES
        EXCLUDE_PATTERNS)
    cmake_parse_arguments(WL2RES "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT WL2RES_ROOT OR NOT WL2RES_PREFIX)
        message(FATAL_ERROR "wl2_add_embedded_resources requires ROOT and PREFIX")
    endif()

    if(NOT WL2RES_COMPRESSION)
        set(WL2RES_COMPRESSION "AUTO")
    endif()
    string(TOUPPER "${WL2RES_COMPRESSION}" WL2RES_COMPRESSION)

    foreach(_pattern IN LISTS WL2RES_EXCLUDE_PATTERNS)
        wl2_glob_to_regex("${_pattern}" _regex)
        list(APPEND _exclude_regexes "${_regex}")
    endforeach()

    macro(wl2_is_resource_excluded file out_var)
        set(${out_var} FALSE)
        get_filename_component(_exclude_name "${file}" NAME)
        foreach(_exclude_regex IN LISTS _exclude_regexes)
            if("${file}" MATCHES "${_exclude_regex}" OR "${_exclude_name}" MATCHES "${_exclude_regex}")
                set(${out_var} TRUE)
            endif()
        endforeach()
    endmacro()

    macro(wl2_note_resource_file file policy explicit)
        if(IS_ABSOLUTE "${file}")
            message(FATAL_ERROR "Resource file paths must be relative to ROOT: ${file}")
        endif()
        if(NOT EXISTS "${WL2RES_ROOT}/${file}")
            message(FATAL_ERROR "Resource file does not exist: ${WL2RES_ROOT}/${file}")
        endif()
        if(IS_DIRECTORY "${WL2RES_ROOT}/${file}")
            message(FATAL_ERROR "Resource file path is a directory; use *_DIRECTORIES instead: ${file}")
        endif()

        string(MD5 _file_key "${file}")
        set(_policy_key "_res_policy_${_file_key}")
        set(_explicit_key "_res_explicit_policy_${_file_key}")

        if(DEFINED ${_policy_key})
            if(${explicit})
                if(DEFINED ${_explicit_key} AND NOT "${${_policy_key}}" STREQUAL "${policy}")
                    message(FATAL_ERROR "Resource file has conflicting explicit policies: ${file}")
                endif()
                set(${_policy_key} "${policy}")
                set(${_explicit_key} TRUE)
            endif()
        else()
            list(APPEND _all_files "${file}")
            set(${_policy_key} "${policy}")
            if(${explicit})
                set(${_explicit_key} TRUE)
            endif()
        endif()
    endmacro()

    macro(wl2_collect_resource_directory directory policy)
        if(IS_ABSOLUTE "${directory}")
            message(FATAL_ERROR "Resource directory paths must be relative to ROOT: ${directory}")
        endif()
        if(NOT IS_DIRECTORY "${WL2RES_ROOT}/${directory}")
            message(FATAL_ERROR "Resource directory does not exist: ${WL2RES_ROOT}/${directory}")
        endif()

        file(GLOB_RECURSE _dir_files
            LIST_DIRECTORIES false
            RELATIVE "${WL2RES_ROOT}"
            CONFIGURE_DEPENDS
            "${WL2RES_ROOT}/${directory}/*")
        foreach(_dir_file IN LISTS _dir_files)
            wl2_is_resource_excluded("${_dir_file}" _is_excluded)
            if(NOT _is_excluded)
                wl2_note_resource_file("${_dir_file}" "${policy}" FALSE)
            endif()
        endforeach()
    endmacro()

    set(_all_files)
    foreach(_directory IN LISTS WL2RES_DIRECTORIES)
        wl2_collect_resource_directory("${_directory}" "${WL2RES_COMPRESSION}")
    endforeach()
    foreach(_directory IN LISTS WL2RES_STORE_DIRECTORIES)
        wl2_collect_resource_directory("${_directory}" "STORE")
    endforeach()
    foreach(_directory IN LISTS WL2RES_COMPRESS_DIRECTORIES)
        wl2_collect_resource_directory("${_directory}" "COMPRESS")
    endforeach()
    foreach(_directory IN LISTS WL2RES_AUTO_DIRECTORIES)
        wl2_collect_resource_directory("${_directory}" "AUTO")
    endforeach()

    foreach(_file IN LISTS WL2RES_FILES)
        wl2_note_resource_file("${_file}" "${WL2RES_COMPRESSION}" FALSE)
    endforeach()
    foreach(_file IN LISTS WL2RES_STORE_FILES)
        wl2_note_resource_file("${_file}" "STORE" TRUE)
    endforeach()
    foreach(_file IN LISTS WL2RES_COMPRESS_FILES)
        wl2_note_resource_file("${_file}" "COMPRESS" TRUE)
    endforeach()
    foreach(_file IN LISTS WL2RES_AUTO_FILES)
        wl2_note_resource_file("${_file}" "AUTO" TRUE)
    endforeach()

    if(NOT _all_files)
        message(FATAL_ERROR "wl2_add_embedded_resources requires FILES, *_FILES, DIRECTORIES, or *_DIRECTORIES")
    endif()
    list(SORT _all_files)
    set(_resource_dependencies)
    foreach(_file IN LISTS _all_files)
        list(APPEND _resource_dependencies "${WL2RES_ROOT}/${_file}")
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_resource_dependencies})

    if(NOT WL2RES_OUTPUT)
        set(WL2RES_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${target_name}_embedded_resources.cpp")
    endif()

    file(WRITE "${WL2RES_OUTPUT}" "#include <wl2/resources.h>\n\nnamespace {\n")
    foreach(_file IN LISTS _all_files)
        file(READ "${WL2RES_ROOT}/${_file}" _content HEX)
        string(SHA256 _hash "${_content}")
        wl2_rle_encode_hex("${_content}" _compressed)
        string(LENGTH "${_content}" _raw_hex_len)
        string(LENGTH "${_compressed}" _compressed_hex_len)

        string(MD5 _file_key "${_file}")
        set(_policy "${_res_policy_${_file_key}}")

        if(_policy STREQUAL "COMPRESS")
            set(_stored_hex "${_compressed}")
            set(_compression "wl2::ResourceCompression::Rle")
        elseif(_policy STREQUAL "AUTO" AND _compressed_hex_len LESS _raw_hex_len)
            set(_stored_hex "${_compressed}")
            set(_compression "wl2::ResourceCompression::Rle")
        elseif(_policy STREQUAL "STORE" OR _policy STREQUAL "AUTO")
            set(_stored_hex "${_content}")
            set(_compression "wl2::ResourceCompression::Stored")
        else()
            message(FATAL_ERROR "Unknown resource COMPRESSION policy: ${_policy}")
        endif()

        string(MAKE_C_IDENTIFIER "${_file}" _ident)
        string(SUBSTRING "${_file_key}" 0 8 _file_key_short)
        set(_ident "${_ident}_${_file_key_short}")
        wl2_append_resource_array("${WL2RES_OUTPUT}" "${_ident}" "${_stored_hex}")
        math(EXPR _original_size "${_raw_hex_len} / 2")
        string(LENGTH "${_stored_hex}" _stored_hex_len)
        math(EXPR _stored_size "${_stored_hex_len} / 2")
        set(_res_original_size_${_ident} "${_original_size}")
        set(_res_stored_size_${_ident} "${_stored_size}")
        set(_res_hash_${_ident} "${_hash}")
        set(_res_compression_${_ident} "${_compression}")
        set(_res_stored_hex_${_ident} "${_stored_hex}")
    endforeach()
    set(_inspection_table "WL2_RESOURCE_TABLE_V1\n")
    foreach(_file IN LISTS _all_files)
        string(MD5 _file_key "${_file}")
        string(MAKE_C_IDENTIFIER "${_file}" _ident)
        string(SUBSTRING "${_file_key}" 0 8 _file_key_short)
        set(_ident "${_ident}_${_file_key_short}")
        if(_res_compression_${_ident} STREQUAL "wl2::ResourceCompression::Rle")
            set(_inspection_compression "rle")
        else()
            set(_inspection_compression "stored")
        endif()
        string(APPEND _inspection_table
            "${WL2RES_PREFIX}/${_file}\t${_inspection_compression}\t${_res_original_size_${_ident}}\t${_res_stored_size_${_ident}}\t${_res_hash_${_ident}}\t${_res_stored_hex_${_ident}}\n")
    endforeach()
    string(APPEND _inspection_table "WL2_RESOURCE_TABLE_END\n")
    wl2_cpp_escape_string("${_inspection_table}" _inspection_table_cpp)
    file(APPEND "${WL2RES_OUTPUT}" "extern \"C\" const char wl2_resource_inspection_table[] __attribute__((used)) = \"${_inspection_table_cpp}\";\n")
    file(APPEND "${WL2RES_OUTPUT}" "}\n\nvoid wl2_register_embedded_resources(wl2::ResourceStore& store) {\n")
    foreach(_file IN LISTS _all_files)
        string(MD5 _file_key "${_file}")
        string(MAKE_C_IDENTIFIER "${_file}" _ident)
        string(SUBSTRING "${_file_key}" 0 8 _file_key_short)
        set(_ident "${_ident}_${_file_key_short}")
        wl2_cpp_escape_string("${WL2RES_PREFIX}/${_file}" _resource_path)
        file(APPEND "${WL2RES_OUTPUT}" "  store.addResource(wl2::ResourceEntry{\"${_resource_path}\", ${_res_original_size_${_ident}}, ${_res_stored_size_${_ident}}, ${_res_compression_${_ident}}, \"${_res_hash_${_ident}}\", \"\", 0}, res_${_ident}, ${_res_stored_size_${_ident}});\n")
    endforeach()
    file(APPEND "${WL2RES_OUTPUT}" "}\n")

    target_sources(${target_name} PRIVATE "${WL2RES_OUTPUT}")
endfunction()

function(wl2_add_javascript_executable target_name)
    set(options)
    set(oneValueArgs ROOT ENTRY PREFIX OUTPUT CORE_TARGET MANIFEST)
    set(multiValueArgs
        FILES STORE_FILES COMPRESS_FILES AUTO_FILES
        DIRECTORIES STORE_DIRECTORIES COMPRESS_DIRECTORIES AUTO_DIRECTORIES
        EXCLUDE_PATTERNS LINK_LIBRARIES INCLUDES STATIC_MODULES
        FILESYSTEM_READ_ROOTS)
    cmake_parse_arguments(WL2JS "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(WL2JS_MANIFEST)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${WL2JS_MANIFEST}")
        wl2_read_resource_manifest("${WL2JS_MANIFEST}" _wl2js_manifest)
        set(WL2JS_ROOT "${_wl2js_manifest_ROOT}")
        set(WL2JS_ENTRY "${_wl2js_manifest_ENTRY}")
        set(WL2JS_PREFIX "${_wl2js_manifest_PREFIX}")
        set(WL2JS_STORE_FILES "${_wl2js_manifest_STORE_FILES}")
        set(WL2JS_COMPRESS_FILES "${_wl2js_manifest_COMPRESS_FILES}")
        set(WL2JS_AUTO_FILES "${_wl2js_manifest_AUTO_FILES}")
        set(WL2JS_STORE_DIRECTORIES "${_wl2js_manifest_STORE_DIRECTORIES}")
        set(WL2JS_COMPRESS_DIRECTORIES "${_wl2js_manifest_COMPRESS_DIRECTORIES}")
        set(WL2JS_AUTO_DIRECTORIES "${_wl2js_manifest_AUTO_DIRECTORIES}")
        set(WL2JS_EXCLUDE_PATTERNS "${_wl2js_manifest_EXCLUDE_PATTERNS}")
    endif()

    if(NOT WL2JS_ROOT OR NOT WL2JS_ENTRY)
        message(FATAL_ERROR "wl2_add_javascript_executable requires ROOT and ENTRY")
    endif()

    if(NOT WL2JS_PREFIX)
        set(WL2JS_PREFIX "wl2:/app")
    endif()

    if(IS_ABSOLUTE "${WL2JS_ENTRY}")
        message(FATAL_ERROR "ENTRY must be relative to ROOT: ${WL2JS_ENTRY}")
    endif()

    if(NOT WL2JS_CORE_TARGET)
        if(TARGET wl2_core)
            set(WL2JS_CORE_TARGET wl2_core)
        elseif(TARGET winglib2::wl2_core)
            set(WL2JS_CORE_TARGET winglib2::wl2_core)
        else()
            message(FATAL_ERROR "wl2_add_javascript_executable could not find wl2_core; pass CORE_TARGET explicitly")
        endif()
    endif()

    if(NOT WL2JS_OUTPUT)
        set(WL2JS_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/${target_name}_main.cpp")
    endif()

    set(_entry_specifier "${WL2JS_PREFIX}/${WL2JS_ENTRY}")
    set(_generated_source "#include <wl2/wl2.h>\n")
    foreach(_include IN LISTS WL2JS_INCLUDES)
        string(APPEND _generated_source "#include <${_include}>\n")
    endforeach()
    string(APPEND _generated_source "\n#include <iostream>\n#include <utility>\n\nvoid wl2_register_embedded_resources(wl2::ResourceStore& store);\n\nint main() {\n    wl2::RuntimeOptions options;\n    options.allowFilesystem = false;\n")
    foreach(_module IN LISTS WL2JS_STATIC_MODULES)
        string(APPEND _generated_source "    options.staticModules.push_back(${_module});\n")
    endforeach()
    if(WL2JS_FILESYSTEM_READ_ROOTS)
        string(APPEND _generated_source "    options.allowFilesystemReads = true;\n")
        foreach(_root IN LISTS WL2JS_FILESYSTEM_READ_ROOTS)
            string(APPEND _generated_source "    options.filesystemReadRoots.emplace_back(\"${_root}\");\n")
        endforeach()
    endif()
    string(APPEND _generated_source "    wl2::Runtime runtime{std::move(options)};\n    wl2_register_embedded_resources(runtime.resources());\n    auto result = runtime.runModule(\"${_entry_specifier}\");\n    if (!result) {\n        std::cerr << result.error().code() << \": \" << result.error().message() << '\\n';\n        return 1;\n    }\n    return result.value();\n}\n")
    file(WRITE "${WL2JS_OUTPUT}" "${_generated_source}")

    add_executable(${target_name} "${WL2JS_OUTPUT}")
    target_link_libraries(${target_name} PRIVATE ${WL2JS_CORE_TARGET} ${WL2JS_LINK_LIBRARIES})

    set(_resource_args
        ROOT "${WL2JS_ROOT}"
        PREFIX "${WL2JS_PREFIX}")
    foreach(_arg
            FILES STORE_FILES COMPRESS_FILES AUTO_FILES
            DIRECTORIES STORE_DIRECTORIES COMPRESS_DIRECTORIES AUTO_DIRECTORIES
            EXCLUDE_PATTERNS)
        if(WL2JS_${_arg})
            list(APPEND _resource_args ${_arg} ${WL2JS_${_arg}})
        endif()
    endforeach()

    if(NOT WL2JS_FILES AND NOT WL2JS_STORE_FILES AND NOT WL2JS_COMPRESS_FILES AND NOT WL2JS_AUTO_FILES
            AND NOT WL2JS_DIRECTORIES AND NOT WL2JS_STORE_DIRECTORIES AND NOT WL2JS_COMPRESS_DIRECTORIES
            AND NOT WL2JS_AUTO_DIRECTORIES)
        list(APPEND _resource_args FILES "${WL2JS_ENTRY}")
    endif()

    wl2_add_embedded_resources(${target_name} ${_resource_args})
endfunction()
